[package]
name = "pulse-m2-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pulse-nq-load-support = { path = "../pulse-nq-load-support" }
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
sha2.workspace = true
toml.workspace = true
rand_core.workspace = true

[lints]
workspace = true
