[package]
name = "pulse-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "sha2/std", "dep:serde_jcs"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false }
serde_jcs = { workspace = true, optional = true }

[lints]
workspace = true
